### PR TITLE
migrate-tests-to-v2: auto_start_test.py

### PR DESCRIPTION
**Pull request by aleksandr-kotlyar**
Relates to #203

### CODE REVIEW

**Comment by yashaka** [comment]
Isn't all this covered here?
image

**Comment by aleksandr-kotlyar** [comment]
> Isn't all this covered here?
> image

Seems it have already been useless, cause all 4 tests are the same :) i don't understand why first two of them names manual and the last two - autostart - they are totally the same.

Should i delete this module in this PR?

**Comment by yashaka** [comment]
let's remove it, yep

**Comment by aleksandr-kotlyar** [comment]
> let's remove it, yep

Removed. :)

**Pull request merged**
