### PR TITLE
delete import aliases from __init__ (#265)

### LINKED ISSUE #265: consider to remove aliases from __init__.py
## Example
```
from selene.core.entity import Browser as _custom_browser, Config as _custom_config_for_custom_browser
Config = _custom_config_for_custom_browser
Browser = _custom_browser

from selene.support import by as _by_style_selectors
by = _by_style_selectors

from selene.support.conditions import be as _be_style_conditions
be = _be_style_conditions
```

## Proposal solution
```
from selene.core.entity import Browser as _custom_browser, Config as _custom_config_for_custom_browser
from selene.support import by as _by_style_selectors
from selene.support.conditions import be as _be_style_conditions
```
Already have tested without aliases on python 3.7. I have run all tests on current master and they all passed.

## Consider
Does selene still need these aliases? And for what?

### PR DESCRIPTION
**Pull request by aleksandr-kotlyar**
Closes #265

### CODE REVIEW

**Comment by yashaka** [comment]
just check please in PyCharm and VSCode that we can we can see the suggested import via Quick Fix in PyCharm and VSCode. If yes, we can merge this PR

**Comment by aleksandr-kotlyar** [comment]
> just check please in PyCharm and VSCode that we can we can see the suggested import via Quick Fix in PyCharm and VSCode. If yes, we can merge this PR

### Tested
Tested on `from selene import have` - see screenshots.
#### Pycharm 2020.3 - yes it does autocomplete. 
image
#### VS Code Version: 1.52.1 - yes it does autocomplete.
image

**Comment by yashaka** [comment]
Heh, since quick fixing imports does not work neither in PyCharm nor in VSCode - let's keep the current workarounds.
And let's find time to file issues for both PyCharm and VSCode... Maybe we can move this discussioin into some selene issue, if we have not created it yet

**Comment by aleksandr-kotlyar** [comment]
> Maybe we can move this discussioin into some selene issue, if we have not created it yet

Moved to the linked issue #265. 
Closing PR.

**Pull request closed without merging**
