### PR TITLE
solution for Selene Selenium 3.0 Actions error #113

### PR DESCRIPTION
**Pull request by evgenynalivayko**
I do not know how to build a full version of selene (I only forged part of the code), but if the added lines are in this file, the problem is solved

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
@evgenynalivayko to build selene module you can use 
```python setup.py bdist_sheel```

**Comment by SergeyPirogov** [comment]
@Yup, it fixes some errors, but still double click doesn't work well

**Comment by daveenguyen** [comment]
If the double click problem is on FF, it's an issue that's in testing.
https://github.com/mozilla/geckodriver/issues/661

**Comment by SergeyPirogov** [comment]
OK, will wait fix for this

**Pull request merged**
