### PR TITLE
Extend interaction with pages'  elements

### PR DESCRIPTION
**Pull request by extsoft**

### CODE REVIEW

**Comment by yashaka** [comment]
Oh, man, thank you for this PR. Just it will be a hard task to accept it :). But I will try, hopefully, next week. 

The problem is that I have refactored the implementation and changed the API a bit. 
From 
```
elements.assure(texts, "1", "2", "3")
```
to
```
elements.assure(texts("1", "2", "3"))
```
Unfortunately I had no time to commit my changes... But I plan to do that in nearest two weeks. 
I will commit them, and then will do a merge of your changes.

Thanks one more time for your work!

**Comment by extsoft** [comment]
Hello! 
How is it going? 

I'm still waiting for your feedback. The reason why I'm writing you I have been involved to new project and wait for some selene's features from this PR. I happy to answer any questions/suggestions.

Thank you in advance!

**Comment by yashaka** [comment]
Hi,

Tough times on my side:)

I have scheduled this Thursday to work on Selene a bit. Hope I will succeed.
Sorry for waiting...

Thanks
Iakiv

**Comment by yashaka** [comment]
Hi, Dmytro,

I was working hard last days on Selene... Seems like my refactoring is
coming to the end.
I removed "LoadingComponent" functionality (please notify me if you were
using it) - that one about "to_open" methods. I think that such "smartness"
actually hide test logic from the place where it should be... These may
tend to problems in support of tests with the time...
Also I made implementation faster and more readable in code. The
implementation is also became less DRY sometimes, but easier to understand
and support(I hope at least:)). I plan to work further on simplifying the
implementation.
Added some tests.

Unfortunately next week and a half will be even more tough for me. And I
will not be able to merge your Pull Request into "new implementation".

If you are in a rush, you can help me and first merge my last changes into
your version (you should not need another PR, the current one should
include any further changes to your branch, if you made the Pull Request
based on the branch). Then it will be easier for me to accept your PR.

If you agree, I will commit my changes tomorrow or after tomorrow so you
can do your part.

What do you say?

P.S.
One more sorry for the slowness on my side... After middle of December I
should have much more time for Selene, since I will move to Brazil, and
will be less busy with my normal work...

**Comment by extsoft** [comment]
I’m going to merge your changes into my branch.

Just wait for it.

Thanks,
Dmytro

> 30 лист. 2015 р. о 03:31 yashaka <notifications@github.com> написав(ла):
> 
> Hi, Dmytro,
> 
> I was working hard last days on Selene... Seems like my refactoring is
> coming to the end.
> I removed "LoadingComponent" functionality (please notify me if you were
> using it) - that one about "to_open" methods. I think that such "smartness"
> actually hide test logic from the place where it should be... These may
> tend to problems in support of tests with the time...
> Also I made implementation faster and more readable in code. The
> implementation is also became less DRY sometimes, but easier to understand
> and support(I hope at least:)). I plan to work further on simplifying the
> implementation.
> Added some tests.
> 
> Unfortunately next week and a half will be even more tough for me. And I
> will not be able to merge your Pull Request into "new implementation".
> 
> If you are in a rush, you can help me and first merge my last changes into
> your version (you should not need another PR, the current one should
> include any further changes to your branch, if you made the Pull Request
> based on the branch). Then it will be easier for me to accept your PR.
> 
> If you agree, I will commit my changes tomorrow or after tomorrow so you
> can do your part.
> 
> What do you say?
> 
> P.S.
> One more sorry for the slowness on my side... After middle of December I
> should have much more time for Selene, since I will move to Brazil, and
> will be less busy with my normal work...
>

**Comment by yashaka** [comment]
Ok, I will commit them soon and notify you.


—

**Comment by yashaka** [comment]
Committed. Feel free to do the merge on your side.

**Comment by yashaka** [comment]
Feel free to ask questions regarding details of new implementation.
I had no time to provide good docs for new implementation...

**Comment by extsoft** [comment]
I have a lot of questions. IMHO last implementation is very complicated.

I would like to discuss SELENE’s vision. Could you please find me in Skype (my account: dserdyuk)?

Looking forward to productive discussions.

Thank you in advance!
Best regards,
Dmytro

**Comment by yashaka** [comment]
I have send contact request.

In short:

The main changes in implementation are:

1.
Removing main part of "implicit waiting" from __getattr__ and adding it
explicitly to all methods calls. This is less dry but gives more
straightforward code
And also makes support and further implementation much easier. It happened
that "implicit waiting" in __getattr__ makes selene slow and is prone to
bugs. And debugging such bugs are complete pain. It happenned that
__getattr__ is (being something very simple initially) a complete mess in
further development. That's why the goal is to use is as less as possible.
In other words - I removed *magic* from implementation.

2. Removing IFs from SElment initializers via creating more classes.
Now we have more classes but no IFs in implementation. Actually this is a
standard solution in modern software development. This looks not easy at
first sight. But it is simpler. Simple is not the same as easy. And often
"simplicity" is better than "easy". Google for this :)

Via removing IFs we get more straigtforward code. Now we have more things,
but each thing has less responsibilities. Thus in future it's easier to
debug, improve or refactor.

You may think that all this is overcomplicated. But I made all this
"complications" only because I found too many bugs in Selene, when I
started to cover it with tests. In addition "old" Selene happened to be too
slow. Even now it's not fast enough, but much faster than older version, at
least I hope so :)

3. And one more reason why I made so many "wrapper-classes". Actually this
is the main reason. Otherwise - you could not write the following code:

visibleTaks = ss("#todo-list>li").filter(visible)

open("http://todomvc4tasj.herocu.com")
add("a", "b", "c")
toggle("a")
visibleTasks.assure(exact_texts("b", "c"))


This code will not work with old Selene, because it will try to filter
tasks in first line while we are still even not on the needed page.
This is because filter makes filtering, but does not create a "proxy"
filtered collection.

Selenide can do the latter - "creating proxy instead of actual doing". And
this is good because the idea of Selene is to be "the simplest DSL to write
selenium tests, without taking care of technical details". You just define
small blocks to be reused, and build your house from these blocks.

By the way, the number 3 "change" reflects the same implementation that
Selenide is based on. The "Selene vision" is to take best from Selenide and
other implementations... In fact, the Selene is a port of Selenide +
htmlelements. So it's not a suprise that it follows the "selenide" way.

In addition there are other changes:

- Removing support for "Loadable Component" pattern - which is "making it
more simple not complicated" in fact in both -  implementation and usage.
- Removing automatic browser management - which is also the way to
simplicity (one day we can add this management, but it's pretty big and not
trivial task, as I saw... and it needs more time to implement it in good
way)
- Implemented conditions in a bit other more DRY way. But actually current
conditions implementation may be refactored if there will be other better
options.
- Implemented explicit waiting the same way as in Selenium but without its
cons. This makes implementation a bit more common for most selenium users.
Old "explicit waits" implementation was too smart :) And so actually "more
complicated".

Feel free to ask more questions in skype, if needed.

**Pull request closed without merging**
