### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nbdnnm**
Added install webdriver_manager before install selene

### CODE REVIEW

**Comment by yashaka** [comment]
Are you sure this is needed?

image

Selene has webdriver_manager in its dependencies, so it will be installed automatically... 

And according to what I remember - it really works like this simple, just by installing Selene without anything else.

**Comment by nbdnnm** [comment]
image
image

**Comment by yashaka** [comment]
@nbdnnm 
Hm... now I see that this was the specific case with installing Selene from sources...

But don't you think this problem should be fixed in another way then explicit installation of webdriver_manager?

For example... Selene also depends on selenium webdriver, but seems like there is no problem with it, isn't it?
If yes, then at least we would also add the corresponding line to pre-install webdriver too, not just webdriver_manager...

**Comment by nbdnnm** [comment]
yep, agree, it should be smarter
don't know how to make it better, will convert it into an issue

**Comment by yashaka** [comment]
Good good! Let's dig deeper into it!

**Pull request closed without merging**
