### PR TITLE
FIX issue 124

### PR DESCRIPTION
**Pull request by kixiro**
If by.xpath contains utf8 symbols and not condition get UnicodeEncodeError: 'ascii'

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
@kixiro will be nice to have tests for this

**Comment by SergeyPirogov** [comment]
@kixiro There issue with python 3 
https://travis-ci.org/yashaka/selene/builds/220889872

**Comment by kixiro** [comment]
@SergeyPirogov, why the test failed?
tests/examples/todomvc/straightforward_approach/todomvc_test.py::TestTodoMVC::test_filter_tasks FAILED
https://travis-ci.org/yashaka/selene/builds/220904541

**Comment by SergeyPirogov** [comment]
@kixiro I don't know. Seems that your fix causes some side effects.

**Comment by kixiro** [comment]
@SergeyPirogov, I run `tox` local. All tests passed
<pre>
  py27: commands succeeded
  py35: commands succeeded
  congratulations :)
</pre>
How can I restart the tests on the Travis CI?

**Comment by SergeyPirogov** [comment]
@kixiro Restarted. We need them work on Travis. Locally it's locally

**Comment by SergeyPirogov** [comment]
@kixiro Well tests are green , but I think it's better to use https://pythonhosted.org/six/ instead of PY2 = sys.version_info[0] == 2

**Comment by kixiro** [comment]
@SergeyPirogov , Travis CI build is canceled. How can restart build without commits?

**Comment by SergeyPirogov** [comment]
@kixiro job can be restarted only by repo maintainers ;)

**Pull request closed without merging**
